# https://github.com/marketplace/actions/setup-ko
name: Publish Ko

on:
  workflow_dispatch:
  push:
    branches: ['dev']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - uses: ko-build/setup-ko@v0.8
      - run: KO_DEFAULTBASEIMAGE=ghcr.io/mcsps/busybox:latest ko build --bare
