name: Build Docker Container

on:
  workflow_call:
  push:
    branches:
      - dev
    tags:
      - "*"
  #schedule:
  #  - cron: "15 4 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare Dockerfile
        run: |
          sed -i "s|static-app|$REPO_NAME|g" Dockerfile
          cat Dockerfile
        env:
          REPO_NAME: ${{ github.event.repository.name }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: "v2.5.3"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        id: build-push
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ${{ steps.meta.outputs.tags }}
      - name: Sign Push
        run: |
          # old way (won't work in templating because the key must be on the org infrastructure available and we want to use the template on broader way
          #cosign sign --key env://COSIGN_KEY --tlog-upload=false ghcr.io/${{ github.repository }}@${{ steps.build-push.outputs.digest }}
          # new way
          cosign sign -y ghcr.io/${{ github.repository }}@${{ steps.build-push.outputs.digest }}
          # the sign information will be stored in the tlog store. look at the index id on job output
          # rekor-cli get --log-index 454546991 --format json | jq -r '.Body.HashedRekordObj.signature.publicKey.content'| base64 -d| openssl x509 -noout -text
          # this will be shown certificate output of the signed items
          # verify process can be done within certificate information:
          # cosign verify ghcr.io/eumel8/helloworld:wftest --certificate-identity "https://github.com/eumel8/workflow-templates/.github/workflows/container.yaml@refs/tags/0.0.5"   --certificate-oidc-issuer "https://token.actions.githubusercontent.com"
        #env:
        #  COSIGN_KEY: ${{secrets.COSIGN_KEY}}
